name: Test Grid Website
favicon: null
layout_spectrum: 0.5393
typography_spectrum: 0.2810920192860067
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.75
  lightness: 0.5505861015990376
  saturation: 0.2722934444900602
  rhythmicContrast: 0.7484384637791663
purpose: []
